receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # batch metrics before sending to reduce API usage
  batch:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      cluster: demo
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  otlp/tempo:
    endpoint: tempo:4317  # tempo container host and port
    tls:
      insecure: true
  #otlp/jaeger:
  #  endpoint: jaeger:4317  # tempo container host and port
  #  tls:
  #    insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

connectors:

extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus] # mudar para "prometheusremotewrite" para alterar o método de envio no pipeline
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, logging]  # name here should match the exporter name for tempo which is otlp
    logs:
      receivers: [otlp]
      exporters: [loki,logging]